name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allow manual triggering from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Generate the snake animation
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: Mathis428  # Remplace par ton pseudo GitHub ici
          outputs: dist  # Dossier de sortie des fichiers générés

      # Show status of the build (useful for debugging)
      - run: git status

      # Push the changes to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Push to the output branch (to make the animation available)
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output  # Change to the 'output' branch for generated files
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
