name: Generate Snake Animation

on:
  schedule:
    - cron: "0 20 * * *" # Ce workflow se déclenche tous les jours à 20h (UTC)
  workflow_dispatch: # Permet d'exécuter manuellement le workflow

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Mathis428
          outputs: dist/snake.svg

      - name: Push Snake Animation to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
